# Generated by Django 5.2 on 2025-04-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shj",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("appearance", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "original_habitat",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "modern_location",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "source_excerpt",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "source_translation",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("abilities", models.CharField(blank=True, max_length=500, null=True)),
                ("symbolism", models.CharField(blank=True, max_length=1000, null=True)),
                ("category", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "mountain_location",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("chapter", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
